#!/bin/sh /etc/rc.common

START=90
USE_PROCD=1
PROG=/usr/lib/broadlinkac/broadlinkac_service.py

start_service() {
    local enabled=$(uci -q get broadlinkac.settings.enabled)
    [ "$enabled" != "1" ] && return 0

    procd_open_instance
    procd_set_param command /usr/bin/python3 "$PROG"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger broadlinkac
}
